function [d18O_predict, analogidx] = ...
    predictd18Osw(x, AssumptionFiles, printprogress)

% Preallocate vectors
d18O_predict = NaN(numel(x.lat),1);

%Find anaolog locations
for ii = 1:numel(x.lat)
    %Define starting thershold parameters
    if ~isnan(x.sss_anomaly(ii))
        threshold.precipln_anomaly = .5; 
        threshold.sst_anomaly = 5;
        threshold.sss_anomaly_lower = 1.25;
        if x.dist(ii) > 1500
            threshold.dist = x.dist(ii)-750;
        else
            threshold.dist = 750;
        end
        if x.sss_anomaly(ii)>3
            threshold.sss_anomaly_upper = 10;
            threshold.sss_anomaly_lower = 2.5;
        elseif x.sss_anomaly(ii)<-3
            threshold.sss_anomaly_upper = 2.5;
            threshold.sss_anomaly_lower = 10;
        else
            threshold.sss_anomaly_upper = 1.5;
            threshold.sss_anomaly_lower = 1.5;
        end
        if abs(x.lat(ii))>75
            threshold.lat = 25;
        else
            threshold.lat = 12.5;
        end



    analogidx = find(AssumptionFiles.predictsw.sss_anomaly <= x.sss_anomaly(ii)+threshold.sss_anomaly_upper & ...
        AssumptionFiles.predictsw.sss_anomaly >= x.sss_anomaly(ii)-threshold.sss_anomaly_lower &...
        abs(AssumptionFiles.predictsw.lat) <= abs(x.lat(ii))+threshold.lat & ...
        abs(AssumptionFiles.predictsw.lat) >= abs(x.lat(ii))-threshold.lat &...
        AssumptionFiles.predictsw.dist <= x.dist(ii)+threshold.dist & ...
        AssumptionFiles.predictsw.dist >= x.dist(ii)-threshold.dist &...
        AssumptionFiles.predictsw.precipln_anomaly <= x.precipln_anomaly(ii)+threshold.precipln_anomaly & ...
        AssumptionFiles.predictsw.precipln_anomaly >= x.precipln_anomaly(ii)-threshold.precipln_anomaly &...
        AssumptionFiles.predictsw.sst_anomaly <= x.sst_anomaly(ii)+threshold.sst_anomaly & ...
        AssumptionFiles.predictsw.sst_anomaly >= x.sst_anomaly(ii)-threshold.sst_anomaly & ...
        AssumptionFiles.predictsw.lat <= 75);
    
    while numel(analogidx)>100
        threshold.lat = threshold.lat-2.5;
        threshold.sst_anomaly = threshold.sst_anomaly-.5;
        threshold.sss_anomaly_lower = threshold.sss_anomaly_lower-.125;
        threshold.sss_anomaly_upper = threshold.sss_anomaly_upper-.125;
    analogidx = find(AssumptionFiles.predictsw.sss_anomaly <= x.sss_anomaly(ii)+threshold.sss_anomaly_upper & ...
        AssumptionFiles.predictsw.sss_anomaly >= x.sss_anomaly(ii)-threshold.sss_anomaly_lower &...
        abs(AssumptionFiles.predictsw.lat) <= abs(x.lat(ii))+threshold.lat & ...
        abs(AssumptionFiles.predictsw.lat) >= abs(x.lat(ii))-threshold.lat &...
        AssumptionFiles.predictsw.dist <= x.dist(ii)+threshold.dist & ...
        AssumptionFiles.predictsw.dist >= x.dist(ii)-threshold.dist &...
        AssumptionFiles.predictsw.precipln_anomaly <= x.precipln_anomaly(ii)+threshold.precipln_anomaly & ...
        AssumptionFiles.predictsw.precipln_anomaly >= x.precipln_anomaly(ii)-threshold.precipln_anomaly &...
        AssumptionFiles.predictsw.sst_anomaly <= x.sst_anomaly(ii)+threshold.sst_anomaly & ...
        AssumptionFiles.predictsw.sst_anomaly >= x.sst_anomaly(ii)-threshold.sst_anomaly & ...
        AssumptionFiles.predictsw.lat <= 75);
    end
    while numel(analogidx)<25
        threshold.lat = threshold.lat+.25;
        threshold.sst_anomaly = threshold.sst_anomaly+.5;
        threshold.sss_anomaly_lower = threshold.sss_anomaly_lower+.125;
        threshold.sss_anomaly_upper = threshold.sss_anomaly_upper+.125;
        threshold.precipln_anomaly = threshold.precipln_anomaly+.1;
    analogidx = find(AssumptionFiles.predictsw.sss_anomaly <= x.sss_anomaly(ii)+threshold.sss_anomaly_upper & ...
        AssumptionFiles.predictsw.sss_anomaly >= x.sss_anomaly(ii)-threshold.sss_anomaly_lower &...
        abs(AssumptionFiles.predictsw.lat) <= abs(x.lat(ii))+threshold.lat & ...
        abs(AssumptionFiles.predictsw.lat) >= abs(x.lat(ii))-threshold.lat &...
        AssumptionFiles.predictsw.dist <= x.dist(ii)+threshold.dist & ...
        AssumptionFiles.predictsw.dist >= x.dist(ii)-threshold.dist &...
        AssumptionFiles.predictsw.precipln_anomaly <= x.precipln_anomaly(ii)+threshold.precipln_anomaly & ...
        AssumptionFiles.predictsw.precipln_anomaly >= x.precipln_anomaly(ii)-threshold.precipln_anomaly &...
        AssumptionFiles.predictsw.sst_anomaly <= x.sst_anomaly(ii)+threshold.sst_anomaly & ...
        AssumptionFiles.predictsw.sst_anomaly >= x.sst_anomaly(ii)-threshold.sst_anomaly & ...
        AssumptionFiles.predictsw.lat <= 75);
    end
    end
    d18O_predict_all = NaN(length(analogidx),1);
    r2 = NaN(length(analogidx),1);
    for jj = 1:numel(analogidx)
        d18O_predict_all(jj,1) = AssumptionFiles.predictsw.mdl{analogidx(jj)}.predict([x.sss_anomaly(ii),abs(x.lat(ii)),x.dist(ii),x.precipln_anomaly(ii),x.sst_anomaly(ii)]);
        r2(jj,1) = AssumptionFiles.predictsw.mdl{analogidx(jj)}.Rsquared.Adjusted;
    end
    d18O_predict_all(r2<0.75 | d18O_predict_all > 5 | d18O_predict_all < -20, :) = [];
    d18O_predict_all(end+1:end+numel(analogidx)) = AssumptionFiles.predictsw.d18w_obs(analogidx);
    d18O_predict(ii) = median(d18O_predict_all);

    if printprogress
        fprintf('   Completed %.0f of %.0f seawater estimates\n',...
            ii,numel(x.lat));
    end
end

end

